# Generated by Django 6.0.4 on 2026-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkin_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='event_checkin_qr/'),
        ),
    ]
